apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: keycloak-backendconfig
spec:
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 3
    type: HTTPS  # Use HTTPS since your readiness probe is HTTPS
    requestPath: /auth/health/ready  # Match the readiness probe path
    port: 9000  # Match the readiness probe port
