replicaCount: 1

image:
  repository: quay.io/keycloak/keycloak
  tag: latest
  pullPolicy: IfNotPresent

serviceAccount:
  name: keycloak-sa

service:
  type: ClusterIP
  ports:
    http: 8080
    https: 8443
    jgroups: 7600
    health: 9000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/backend-protocol: "https"
    kubernetes.io/ingress.allow-http: "false"
  tls:
    - secretName: keycloak-tls
      hosts:
        - houseofllm.com
  rules:
    - path: /auth/*
      pathType: ImplementationSpecific
      servicePort: http

resources:
  requests:
    memory: "2Gi"
    cpu: "1000m"
  limits:
    memory: "4Gi"
    cpu: "2000m"

env:
  - name: KC_BOOTSTRAP_ADMIN_USERNAME
    valueFromSecret: keycloak-secrets
    key: KC_BOOTSTRAP_ADMIN_USERNAME
  - name: KC_BOOTSTRAP_ADMIN_PASSWORD
    valueFromSecret: keycloak-secrets
    key: KC_BOOTSTRAP_ADMIN_PASSWORD
  - name: KC_DB
    valueFromConfigMap: keycloak-configmap
    key: KC_DB
  - name: KC_PROXY_HEADERS
    valueFromConfigMap: keycloak-configmap
    key: KC_PROXY_HEADERS
  - name: KC_HOSTNAME_STRICT_HTTPS
    valueFromConfigMap: keycloak-configmap
    key: KC_HOSTNAME_STRICT_HTTPS
  - name: KC_DB_URL
    valueFromConfigMap: keycloak-configmap
    key: KC_DB_URL
  - name: KC_HOSTNAME
    valueFromConfigMap: keycloak-configmap
    key: KC_HOSTNAME
  - name: KC_HEALTH_ENABLED
    valueFromConfigMap: keycloak-configmap
    key: KC_HEALTH_ENABLED
  - name: KC_DB_USERNAME
    valueFromSecret: keycloak-secrets
    key: KC_DB_USERNAME
  - name: KC_DB_PASSWORD
    valueFromSecret: keycloak-secrets
    key: KC_DB_PASSWORD
  - name: KC_HTTPS_CERTIFICATE_FILE
    valueFromSecret: keycloak-secrets
    key: KC_HTTPS_CERTIFICATE_FILE
  - name: KC_HTTPS_CERTIFICATE_KEY_FILE
    valueFromSecret: keycloak-secrets
    key: KC_HTTPS_CERTIFICATE_KEY_FILE
  - name: KC_PROXY
    valueFromConfigMap: keycloak-configmap
    key: KC_PROXY
  - name: jgroups.dns.query
    valueFromConfigMap: keycloak-configmap
    key: JGROUPS_DNS_QUERY
  - name: PROXY_ADDRESS_FORWARDING
    valueFromConfigMap: keycloak-configmap
    key: PROXY_ADDRESS_FORWARDING
  - name: KC_METRICS_ENABLED
    valueFromConfigMap: keycloak-configmap
    key: KC_METRICS_ENABLED
  - name: KC_HTTP_ENABLED
    valueFromConfigMap: keycloak-configmap
    key: KC_HTTP_ENABLED
  - name: KC_HTTP_RELATIVE_PATH
    valueFromConfigMap: keycloak-configmap
    key: KC_HTTP_RELATIVE_PATH
  - name: KC_HOSTNAME_URL
    valueFromConfigMap: keycloak-configmap
    key: KC_HOSTNAME_URL
  - name: KC_HOSTNAME_ADMIN_URL
    valueFromConfigMap: keycloak-configmap
    key: KC_HOSTNAME_URL
  - name: JAVA_OPTS_APPEND
    valueFromConfigMap: keycloak-configmap
    key: JAVA_OPTS_APPEND
  - name: KC_LOG_LEVEL
    valueFromConfigMap: keycloak-configmap
    key: KC_LOG_LEVEL



