
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

# Development-specific customization

# Add unique labels for the development overlay
labels:
- includeSelectors: true
  pairs:
    environment: development
patches:
- path: patch-statefulset.yaml
