
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    - host: houseofllm.com  # Your domain
      http:
        paths:
          - path: /auth  # Path for the readiness probe
            pathType: Prefix
            backend:
              service:
                name: keycloak-service
                port:
                  name: https 
  tls:
    - hosts:
        - houseofllm.com
      secretName: keycloak-tls  # Secret containing the TLS certificate
