
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#  - keycloak-secrets.yaml
resources:
  - keycloak-statefulset.yaml
  - keycloak-backend.yaml
  - keycloak-service-account.yaml
  - keycloak-service.yaml
  - keycloak-ingress.yaml

# Specify any common labels
labels:
- includeSelectors: true
  pairs:
    app: keycloak
