name: CI-CD
on:
  push: 
    branches: ["main", "develop", "releases/**"]
    paths: ["helm/**", ".github/workflows/**"]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ["main", "develop", "releases/**"]
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy"
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - staging
          - production

env:
  HELM_VERSION: v3.16.4 

permissions:
  id-token: write
  contents: read

jobs:
  validate:
    name: Validate Helm Charts
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Lint Helm Chart
        run: |
          cd helm
          helm lint ./keycloak-chart

      - name: Validate Helm Values
        run: |
          cd helm
          helm template ./keycloak-chart --debug
  
  security_scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: validate
    steps:
      
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy Scan Results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
